# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  All podcast niches â€” add/remove as needed
#  Each podcast gets its own RSS feed, episode folder, cover art
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

PODCASTS = [
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover.png",
        "spotify_url": "https://open.spotify.com/show/033GtiveqJ3namuIWD009h",
        "id":          "ai-tech",
        "title":       "AI Tech Daily",
        "description": "AI Tech Daily is your free daily AI news podcast â€” 5 minutes of the biggest artificial intelligence and tech news every morning. Stay ahead of AI, machine learning, ChatGPT, OpenAI, Google, and the tech industry. New episode every day, completely free.",
        "author":      "AI Tech Daily",
        "category":    "Technology",
        "voice":       "en-US-GuyNeural",
        "rss_file":    "feed.xml",
        "output_dir":  "episodes",
        "hook":        "the AI and tech world",
        "feeds": [
            "https://techcrunch.com/feed/",
            "https://feeds.arstechnica.com/arstechnica/index",
            "https://www.theverge.com/rss/index.xml",
            "https://feeds.feedburner.com/venturebeat/SZYF",
            "https://hnrss.org/frontpage",
        ],
        "keywords": ["ai", "artificial intelligence", "llm", "openai", "google", "microsoft",
                     "nvidia", "robot", "automation", "startup", "chip", "model"],
    },
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover_finance.png",
        "spotify_url": "https://open.spotify.com/show/033GLNkKiAAwbmGsE60q3j",
        "id":          "finance",
        "title":       "Money Minute Daily",
        "description": "Your free daily 5-minute finance podcast. Stock market, investing, personal finance, and economic news every morning. The smartest 5 minutes for your money.",
        "author":      "Money Minute Daily",
        "category":    "Business",
        "voice":       "en-US-JennyNeural",
        "rss_file":    "feeds/finance.xml",
        "output_dir":  "episodes/finance",
        "hook":        "the world of finance and markets",
        "feeds": [
            "https://feeds.bloomberg.com/markets/news.rss",
            "https://www.cnbc.com/id/10000664/device/rss/rss.html",
            "https://feeds.marketwatch.com/marketwatch/topstories/",
            "https://finance.yahoo.com/news/rssindex",
            "https://www.investopedia.com/feedbuilder/feed/getfeed/?feedName=rss_headline",
        ],
        "keywords": ["stock", "market", "invest", "economy", "fed", "rate", "inflation",
                     "earnings", "profit", "gdp", "dollar", "finance", "fund", "crypto"],
    },
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover_health.png",
        "spotify_url": "https://open.spotify.com/show/033GLQnAfaU0XNh7X3YGnc",
        "id":          "health",
        "title":       "Health Edge Daily",
        "description": "Daily health and longevity news in 5 minutes. Science-backed health tips, medical breakthroughs, nutrition, fitness, and longevity research every morning.",
        "author":      "Health Edge Daily",
        "category":    "Health",
        "voice":       "en-AU-NatashaNeural",
        "rss_file":    "feeds/health.xml",
        "output_dir":  "episodes/health",
        "hook":        "health, medicine, and longevity",
        "feeds": [
            "https://www.medicalnewstoday.com/rss/",
            "https://feeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC",
            "https://rss.health.harvard.edu/",
            "https://www.sciencedaily.com/rss/health_medicine.xml",
            "https://www.nih.gov/feeds/newsinhealth.rss",
        ],
        "keywords": ["health", "study", "research", "cancer", "drug", "diet", "exercise",
                     "longevity", "brain", "heart", "mental", "vitamin", "disease", "cure"],
    },
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover_startup.png",
        "spotify_url": "https://open.spotify.com/show/033GLTGJK1negHtroqey6L",
        "id":          "startup",
        "title":       "Startup Wire Daily",
        "description": "Daily 5-minute startup and venture capital news. Funding rounds, founder stories, product launches, and the business ideas changing the world.",
        "author":      "Startup Wire Daily",
        "category":    "Business",
        "voice":       "en-GB-RyanNeural",
        "rss_file":    "feeds/startup.xml",
        "output_dir":  "episodes/startup",
        "hook":        "the startup and venture capital world",
        "feeds": [
            "https://techcrunch.com/category/startups/feed/",
            "https://feeds.feedburner.com/venturebeat/SZYF",
            "https://hnrss.org/frontpage",
            "https://www.sifted.eu/feed",
            "https://feeds.feedburner.com/entrepreneur/latest",
        ],
        "keywords": ["startup", "funding", "raise", "series", "venture", "founder", "launch",
                     "ipo", "acquisition", "valuation", "seed", "product", "saas", "billion"],
    },
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover_crypto.png",
        "spotify_url": "https://open.spotify.com/show/033GLYTHebKZukpcuhbMyr",
        "id":          "crypto",
        "title":       "Crypto Daily Brief",
        "description": "Your free daily 5-minute crypto and Web3 news podcast. Bitcoin, Ethereum, DeFi, NFTs, and blockchain news every morning. Stay ahead of the crypto market.",
        "author":      "Crypto Daily Brief",
        "category":    "Technology",
        "voice":       "en-US-GuyNeural",
        "rss_file":    "feeds/crypto.xml",
        "output_dir":  "episodes/crypto",
        "hook":        "the crypto and Web3 world",
        "feeds": [
            "https://www.coindesk.com/arc/outboundfeeds/rss/",
            "https://cointelegraph.com/rss",
            "https://decrypt.co/feed",
            "https://bitcoinmagazine.com/.rss/full/",
            "https://cryptoslate.com/feed/",
        ],
        "keywords": ["bitcoin", "ethereum", "crypto", "blockchain", "defi", "nft", "web3",
                     "token", "wallet", "exchange", "btc", "eth", "solana", "binance"],
    },
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover_trending.png",
        "spotify_url": "https://open.spotify.com/show/033GM2aL4HubkizmHcyPFM",
        "id":          "world-news",   # id/feed/dirs unchanged - platform URLs + history stay
        "title":       "Trending Now Daily",
        "description": "The stories the whole internet is searching for, explained in 5 minutes. Every day we take Google's top trending searches and tell you what actually happened and why everyone is suddenly talking about it. News, viral moments, and the answers behind the search spikes - clear, fast, free.",
        "author":      "Trending Now Daily",
        "category":    "News",
        "voice":       "en-GB-SoniaNeural",
        "rss_file":    "feeds/world.xml",
        "output_dir":  "episodes/world",
        "hook":        "the stories everyone is searching for right now",
        "mode":        "trends",  # stories come from Google Trends, not the feeds below
        "feeds": [
            "https://feeds.bbci.co.uk/news/world/rss.xml",
            "https://rss.reuters.com/reuters/worldNews",
            "https://www.theguardian.com/world/rss",
            "https://feeds.npr.org/1001/rss.xml",
            "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        ],
        "keywords": ["trending", "viral", "google trends", "why is it trending", "breaking",
                     "news", "search", "internet", "explained", "today"],
    },
    {
        "cover_url":   "https://sameer1337.github.io/ai-tech-podcast/assets/cover_truecrime.png",
        "spotify_url": "https://open.spotify.com/show/033GM4g8k8DNyc4KH3R14v",
        "id":          "true-crime",
        "title":       "True Crime Digest",
        "description": "Daily true crime stories in 5 minutes. Real cases, investigations, courtroom drama, and justice served â€” every morning. The most gripping podcast on your commute.",
        "author":      "True Crime Digest",
        "category":    "True Crime",
        "voice":       "en-US-JennyNeural",
        "rss_file":    "feeds/truecrime.xml",
        "output_dir":  "episodes/truecrime",
        "hook":        "true crime and justice",
        "feeds": [
            "https://www.crimeonline.com/feed/",
            "https://lawandcrime.com/feed/",
            "https://www.courthousenews.com/feed/",
        ],
        "keywords": ["murder", "crime", "arrest", "trial", "verdict", "police", "court",
                     "sentence", "victim", "detective", "suspect", "investigation", "case"],
    },
]

# Quick lookup by id
PODCAST_MAP = {p["id"]: p for p in PODCASTS}

